-- bcnf-resolved.sql
-- Resolves the BCNF issue by separating trainer_name -> certification_name
-- into its own table. The remaining assignment table contains only key-based facts.

DROP TABLE IF EXISTS employee_training_assignment;
DROP TABLE IF EXISTS trainer_certification;
DROP TABLE IF EXISTS child;
DROP TABLE IF EXISTS employee_training;
DROP TABLE IF EXISTS job_title;
DROP TABLE IF EXISTS employee;

CREATE TABLE job_title (
    title TEXT PRIMARY KEY,
    salary NUMERIC(10, 2) NOT NULL
);

CREATE TABLE employee (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dob DATE NOT NULL,
    title TEXT NOT NULL REFERENCES job_title (title)
);

CREATE TABLE child (
    employee_id INTEGER NOT NULL,
    birth_order INTEGER NOT NULL,
    first_name TEXT NOT NULL,
    PRIMARY KEY (employee_id, birth_order),
    FOREIGN KEY (employee_id) REFERENCES employee (employee_id)
);

CREATE TABLE trainer_certification (
    trainer_name TEXT PRIMARY KEY,
    certification_name TEXT NOT NULL
);

CREATE TABLE employee_training_assignment (
    employee_id INTEGER NOT NULL,
    trainer_name TEXT NOT NULL,
    PRIMARY KEY (employee_id, trainer_name),
    FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    FOREIGN KEY (trainer_name) REFERENCES trainer_certification (trainer_name)
);

INSERT INTO job_title (title, salary)
VALUES
    ('Analyst', 65000.00),
    ('Manager', 90000.00);

INSERT INTO employee (employee_id, first_name, last_name, dob, title)
OVERRIDING SYSTEM VALUE
VALUES
    (1000, 'Alice', 'Nguyen', DATE '1988-04-12', 'Analyst'),
    (1001, 'Brian', 'Nguyen', DATE '1985-09-03', 'Analyst'),
    (1002, 'Carla', 'Lopez', DATE '1990-01-21', 'Manager');

INSERT INTO child (employee_id, birth_order, first_name)
VALUES
    (1000, 1, 'Evan'),
    (1000, 2, 'Mia'),
    (1001, 1, 'Noah'),
    (1002, 1, 'Sofia'),
    (1002, 2, 'Lucas');

INSERT INTO trainer_certification (trainer_name, certification_name)
VALUES
    ('Jordan Blake', 'SQL Fundamentals'),
    ('Casey Reed', 'Data Governance'),
    ('Morgan Hale', 'Team Leadership');

INSERT INTO employee_training_assignment (employee_id, trainer_name)
VALUES
    (1000, 'Jordan Blake'),
    (1001, 'Casey Reed'),
    (1002, 'Morgan Hale');
