-- first.sql
-- Unnormalized starting point:
-- 1NF violation: children are stored as a JSON array inside employee.
-- 3NF violation: title -> salary.
-- BCNF violation (carried through later versions): trainer_name -> certification_name
-- in employee_training, where the candidate keys are
-- (employee_id, certification_name) and (employee_id, trainer_name).

DROP TABLE IF EXISTS employee_training;
DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dob DATE NOT NULL,
    title TEXT NOT NULL,
    salary NUMERIC(10, 2) NOT NULL,
    children JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE employee_training (
    employee_id INTEGER NOT NULL,
    certification_name TEXT NOT NULL,
    trainer_name TEXT NOT NULL,
    PRIMARY KEY (employee_id, certification_name),
    UNIQUE (employee_id, trainer_name),
    FOREIGN KEY (employee_id) REFERENCES employee (employee_id)
);

INSERT INTO employee (employee_id, first_name, last_name, dob, title, salary, children)
OVERRIDING SYSTEM VALUE
VALUES
    (
        1000,
        'Alice',
        'Nguyen',
        DATE '1988-04-12',
        'Analyst',
        65000.00,
        '[{"birth_order": 1, "first_name": "Evan"}, {"birth_order": 2, "first_name": "Mia"}]'::jsonb
    ),
    (
        1001,
        'Brian',
        'Nguyen',
        DATE '1985-09-03',
        'Analyst',
        65000.00,
        '[{"birth_order": 1, "first_name": "Noah"}]'::jsonb
    ),
    (
        1002,
        'Carla',
        'Lopez',
        DATE '1990-01-21',
        'Manager',
        90000.00,
        '[{"birth_order": 1, "first_name": "Sofia"}, {"birth_order": 2, "first_name": "Lucas"}]'::jsonb
    );

INSERT INTO employee_training (employee_id, certification_name, trainer_name)
VALUES
    (1000, 'SQL Fundamentals', 'Jordan Blake'),
    (1001, 'Data Governance', 'Casey Reed'),
    (1002, 'Team Leadership', 'Morgan Hale');
