-- second-resolved.sql
-- Resolves the 2NF issue by removing child.last_name.
-- The child last name is implied by the parent employee record.
-- Still violates 3NF because employee.title -> employee.salary.
-- Still violates BCNF because trainer_name -> certification_name in employee_training.

DROP TABLE IF EXISTS child;
DROP TABLE IF EXISTS employee_training;
DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dob DATE NOT NULL,
    title TEXT NOT NULL,
    salary NUMERIC(10, 2) NOT NULL
);

CREATE TABLE child (
    employee_id INTEGER NOT NULL,
    birth_order INTEGER NOT NULL,
    first_name TEXT NOT NULL,
    PRIMARY KEY (employee_id, birth_order),
    FOREIGN KEY (employee_id) REFERENCES employee (employee_id)
);

CREATE TABLE employee_training (
    employee_id INTEGER NOT NULL,
    certification_name TEXT NOT NULL,
    trainer_name TEXT NOT NULL,
    PRIMARY KEY (employee_id, certification_name),
    UNIQUE (employee_id, trainer_name),
    FOREIGN KEY (employee_id) REFERENCES employee (employee_id)
);

INSERT INTO employee (employee_id, first_name, last_name, dob, title, salary)
OVERRIDING SYSTEM VALUE
VALUES
    (1000, 'Alice', 'Nguyen', DATE '1988-04-12', 'Analyst', 65000.00),
    (1001, 'Brian', 'Nguyen', DATE '1985-09-03', 'Analyst', 65000.00),
    (1002, 'Carla', 'Lopez', DATE '1990-01-21', 'Manager', 90000.00);

INSERT INTO child (employee_id, birth_order, first_name)
VALUES
    (1000, 1, 'Evan'),
    (1000, 2, 'Mia'),
    (1001, 1, 'Noah'),
    (1002, 1, 'Sofia'),
    (1002, 2, 'Lucas');

INSERT INTO employee_training (employee_id, certification_name, trainer_name)
VALUES
    (1000, 'SQL Fundamentals', 'Jordan Blake'),
    (1001, 'Data Governance', 'Casey Reed'),
    (1002, 'Team Leadership', 'Morgan Hale');
